declare namespace NodeJS {
  interface ProcessEnv {
    EXPO_PUBLIC_SHOPIFY_DOMAIN?: string;
    EXPO_PUBLIC_SHOPIFY_API_VERSION?: string;
    EXPO_PUBLIC_SHOPIFY_STOREFRONT_TOKEN?: string;
    EXPO_PUBLIC_GOOGLE_PLACES_API_KEY?: string;
    EXPO_PUBLIC_FIREBASE_API_KEY?: string;
    EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN?: string;
    EXPO_PUBLIC_FIREBASE_PROJECT_ID?: string;
    EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET?: string;
    EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID?: string;
    EXPO_PUBLIC_FIREBASE_APP_ID?: string;
    EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID?: string;
  }
}
